### ISSUE TITLE
very cool plugin!!

### ISSUE THREAD

**Issue by MrDoni98** [ChalkPE/Broadcaster#1]
I have a message from the telegrams do not come to the server ((

**Comment by chalkpe** [comment]
1. Check your bot `token` and `channel` configs. You can get your room's id by `/chat_id` command
2. Check the [privacy mode](https://core.telegram.org/bots#privacy-mode). The bot can't receive normal messages if you enabled that.

![how-to-disable-privacy-mode](https://cloud.githubusercontent.com/assets/9481405/11976144/a2b24e18-a9b8-11e5-8a70-247d0a670aa1.png)

**Comment by MrDoni98** [comment]
thanks :+1:
