### ISSUE TITLE
Is the 1.1-SNAPSHOT stable or should i use the 1.0 on pocketmine.net?

### ISSUE THREAD

**Issue by robske110** [ChalkPE/Broadcaster#3]
I see you made some commits since the version on pocketmine.net and i want to ask if there are any bugs to worry about?

**Comment by chalkpe** [comment]
It's **stable**, but I can't upload new one because PocketMine team doesn't approve my new plugins.
~~#blameshoghi~~

**Comment by robske110** [comment]
Why don't they approve your plugins?

**Comment by chalkpe** [comment]
Maybe that's because of their laziness :(
